# Generated by Django 6.0.2 on 2026-03-20 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contexts', '0001_initial'),
        ('users', '0002_rolepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('context', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_contexts', to='contexts.context')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_contexts', to='users.role')),
            ],
            options={
                'verbose_name': 'Role Context',
                'verbose_name_plural': 'Role Contexts',
                'unique_together': {('role', 'context')},
            },
        ),
    ]
