# Generated by Django 6.0.2 on 2026-03-20 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rolecontext'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='student_id',
            field=models.CharField(blank=True, help_text='Official student ID', max_length=50, null=True, unique=True),
        ),
    ]
