# Generated by Django 6.0.2 on 2026-03-03 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contexts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentityProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_identifier', models.CharField(help_text='Context-specific identifier (e.g., student ID, staff number)', max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('context', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identity_profiles', to='contexts.context')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identity_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Identity Profile',
                'verbose_name_plural': 'Identity Profiles',
                'ordering': ['context'],
                'unique_together': {('user', 'context')},
            },
        ),
    ]
