# Generated by Django 6.0.2 on 2026-03-08 16:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contexts', '0001_initial'),
        ('identities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='identityprofile',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='identityprofile',
            name='display_name',
            field=models.CharField(default='unknown', help_text='Name shown in this context', max_length=200),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='identityprofile',
            constraint=models.UniqueConstraint(fields=('user', 'context'), name='unique_user_context_identity'),
        ),
        migrations.AddConstraint(
            model_name='identityprofile',
            constraint=models.UniqueConstraint(fields=('context', 'external_identifier'), name='unique_identifier_per_context'),
        ),
    ]
