# Generated by Django 6.0.2 on 2026-03-20 11:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contexts', '0001_initial'),
        ('identities', '0002_alter_identityprofile_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='identityprofile',
            index=models.Index(fields=['external_identifier', 'context'], name='identities__externa_0469c1_idx'),
        ),
    ]
