# Generated by Django 6.0.2 on 2026-03-20 13:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identities', '0003_identityprofile_identities__externa_0469c1_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='identityprofile',
            options={'ordering': ['context']},
        ),
        migrations.AlterField(
            model_name='identityprofile',
            name='display_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='identityprofile',
            name='external_identifier',
            field=models.CharField(max_length=150),
        ),
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_type', models.CharField(help_text='e.g. legal, preferred', max_length=50)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Identity',
                'verbose_name_plural': 'Identities',
            },
        ),
        migrations.AddField(
            model_name='identityprofile',
            name='identity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='identities.identity'),
        ),
    ]
