# Generated by Django 6.0.2 on 2026-03-20 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contexts', '0001_initial'),
        ('identities', '0004_alter_identityprofile_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='identityprofile',
            name='unique_user_context_identity',
        ),
        migrations.AddConstraint(
            model_name='identityprofile',
            constraint=models.UniqueConstraint(fields=('identity', 'context'), name='unique_identity_context'),
        ),
        migrations.RemoveField(
            model_name='identityprofile',
            name='user',
        ),
    ]
