# Generated by Django 6.0.2 on 2026-03-20 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identities', '0005_remove_identityprofile_unique_user_context_identity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identityprofile',
            name='identity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='identities.identity'),
        ),
    ]
